abbr:
  #sas: SAs
  0at: At
  0name: Name
  1w: V1
  2w: V2
  2ww: 2W
  3w: V3
  a: A
  aaaa: AAAA
  ac: AC
  acct: Account
  ace: ACE
  acks: ACKs
  acl: ACL
  activ: Activity
  ad: AD
  adt: ADT
  aes128: AES128
  aes192: AES192
  aes256: AES256
  aes: AES
  afsdb: AFSDB
  rds: RDS
  dcom: DCOM
  ah: AH
  rm: RM
  ras: RAS
  ads: ADS
  krbtgt: KRBTGT
  alg: Algorithm
  ansi: ANSI
  api: API
  apis: APIs
  arc: ARC
  arr: Array
  ascii: ASCII
  at: AT
  ata: ATA
  atapi: ATAPI
  atma: ATMA
  atq: ATQ
  atr: Attribute
  att: Attribute
  attr: Attribute
  attrib: Attribute
  attribs: Attributes
  avolid: Volumes
  axfr: AXFR
  backupr: Backup
  bgi: BGI
  bidi: BIDI
  bios: BIOS
  bnd: Binding
  bootp: BOOTP
  brecord: Record
  bstr: String
  buf: Buffer
  buf: Buffer
  buff: Buffer
  bw: Bandwidth
  ca: CA
  cal: CAL
  callenge: Challenge
  cd: CD
  cdc: CDC
  cdfs: CDFS
  cdp: CDP
  cdrom: CDROM
  celt: Count
  cfg: Config
  cgi: CGI
  cid: CID
  clt: Client
  cn: CN
  cnf: Conflict
  col: Column
  com: COM
  compat: Compatibility
  cond: Condition
  cprep: Cluster
  cr: CR
  crl: CRL
  cs: CS
  csd: CSD
  csid: CSID # called subscription id
  css: CSS
  csv: CSV
  cbc: CBC
  crc: CRC
  cts: CTS
  rc4: RC4
  csvfs: CSVFS
  ctrs: Counters
  ctx: Context
  ctxt: Context
  cust: Custom
  cx: X
  cy: Y
  dacl: DACL
  data: Data
  db: DB
  dc: DC
  del: Delete
  des: DES
  descr: Description
  dest: Destination
  dfs: DFS
  dh14: DH14
  dh1: DH1
  dh2048: DH2048
  dh24: DH24
  dh2: DH2
  dh: DH
  dhcid: DHCID
  dhcp: DHCP
  di: DI
  disp: Dispatch
  dl: DL
  dll: DLL
  dm: DM
  dn: DN
  dname: DNAME
  dns: DNS
  kdc: KDC
  dnscname0: CNAME
  dnskey0: KEY
  dnskey: DNSKEY
  dnsmd0: MD
  dnsmf0: MF
  dnsnsec3param0: NSEC3PARAM
  dnsnull0: "NULL"
  dnsnxt0: NXT
  dnsptr0: PTR
  dnsrt0: RT
  dnssig0: SIG
  dnssrv0: SRV
  dnstext0: TXT
  dnstxt0: TXT
  dnswinsr0: WINSR
  dnszero0: ZERO
  dotnet: _NET
  dp: DP
  dra: DRA
  drs: DRS
  ds: DS
  dsa: DSA
  dsets: SETs
  dsid: DSID
  dsm: DSM
  dsms: DSMs
  dsrm: DSRM
  dst: Destination
  dst: Destination
  dte: DTE
  dtm: DTM # dynamic-tunnel mode
  duid: DUID
  duidv6: DUIDV6
  ecdh256: ECDH256
  ecdh384: ECDH384
  ecdsa256: ECDSA256
  ecdsa384: ECDSA384
  eff: Effective
  efi: EFI
  efs: EFS
  eisa: EISA
  eku: EKU
  elm: Element
  elms: Elements
  embd: Embedded
  ent: Entity
  ents: Entries
  ep: EP
  eport: E
  ept: Endpoint
  eq: EQ
  err: Error
  esp: ESP
  eui64: EUI64
  excep: Exception
  failuresw: Failures
  failurew: Failure
  fat32: FAT32
  fat: FAT
  fcb: FCB
  fcfs: FCFS
  fcph3: FCPH3
  fcph: FCPH
  ffffffffw: VQ
  fil: Filter
  fl: FL
  flport: FL
  fport: F
  fqbn: FQBN
  fqdn: FQDN
  fqdn1779: FQDN1779
  fs: FS
  fsm: FSM
  fsmo: FSMO
  ft: FT # fault-tolerant
  ftp: FTP
  gc: GC
  gcm128: GCM128
  gcm192: GCM192
  gcm256: GCM256
  gdi: GDI
  gmac128: GMAC128
  gmac192: GMAC192
  gmac256: GMAC256
  gp: GP
  gpo: GPO
  gport: G
  gpt: GPT
  gteq: GTEQ
  guid: GUID
  guids: GUIDs
  hmac: HMAC
  hba: HBA
  hdd: HDD
  hinfo: HINFO
  hkey: Key
  hr: HResult
  hresult: HResult
  hsf: HSF
  https: HTTPS
  ia64: IA64
  iad: IAD
  iaid: IAID
  ias: IAS
  iata: IATA
  ibm: IBM
  ic: IC
  icm: ICM
  icmp: ICMP
  id: ID
  ide: IDE
  idenrifiers: IDs
  identifier: ID
  idip: IP
  idl: IDL
  idm: IDM
  idrrl: RRL
  ids3: IDs3
  ids: IDs
  idskd: SKD
  idutf8: UTF8
  idx: Index
  ielt: ID
  if: Interface
  ifs: Interfaces
  iid: IID
  iids: IIDs
  iis: IIS
  ike: IKE
  ikev1: IKEv1
  ikev2: IKEv2
  ini: INI
  inq: Inquire
  inst: Instance
  intf: Interface
  inuse: InUse
  invoc: Invocation
  ip4: IPv4
  ip: IP
  ipid: IPID
  ips: IPs
  ipsec: IPsec
  ntlmv1: NTLMv1
  ntlmv2: NTLMv2
  ipv4: IPv4
  ipv6: IPv6
  irp: IRP
  iscsi: ISCSI
  isd: ISD
  isdn: ISDN
  itemw: Item
  itf: Interface
  ixfr: IXFR
  kcc: KCC
  kerb: Kerberos
  keyw: Keyword
  km: KM
  kra: KRA
  ksk: KSK
  lan: LAN
  lanman20: LANMAN20
  lanman21: LANMAN21
  lanman: LANMAN
  lc: LC
  ldap: LDAP
  ldm: LDM
  len: Length
  lic: Client
  lm: LM
  lpc: LPC
  lpft: Values
  lpl: Values
  lport: L
  lsa: LSA
  lua: LUA
  luid: LUID
  luids: LUIDs
  lun: LUN
  lvl: Level
  lznt1: LZNT1
  mac: MAC
  madcap: MADCAP
  mapi: MAPI
  mb: MB
  mb: MB
  mbr: MBR
  mcast: MCast
  mclt: MCLT
  md5: MD5
  mdns: MDNS
  mf2: MF2
  mf3: MF3
  mf: MF
  mfg: Manufacturer
  mg: MG
  mgmt: Management
  mib: MIB
  mif: Interface
  minfo: MINFO
  mm: MM
  mmc: MMC
  mod: Modify
  mpx: MPX
  mqis: MQIS
  mqs: MQS
  mr: MR
  mscope: MScope
  msg: Message
  msr: MSR
  mszip: MSZIP
  mtx: MTX
  mui: MUI
  mx: MX
  naks: NAKs
  nam: Name
  naptr: NAPTR
  nat: NAT
  nc: NC
  ndr: NDR
  neighborsw: Neighbors
  neighborw: Neighbor
  netbios: NetBIOS
  nf: NF
  ngc: NGC
  nl: NL
  nlport: NL
  np: NP
  nport: N
  ns: NS
  nsec3: NSEC3
  nsec: NSEC
  nt4: NT4
  nt: NT
  ntds: NTDS
  ntfs: NTFS
  ntlm: NTLM
  ntowf: NTOWF
  ntp: NTP
  nup: NUp
  nxt: Next
  obj: Object
  oem: OEM
  oid: OID
  ok: OK
  ole: OLE
  op: Operation
  oper: Operator
  ops: Operations
  opsw: Operations
  opw: Operation
  orpc: ORPC
  os2: OS2
  os: OS
  ou: OU
  ous: OUs
  owf: OWF
  oxid: OXID
  p1sas: SAs
  p2sas: SAs
  pac: PAC
  parm: Parameter
  passwd: Password
  patt: Pattern
  pb: PB
  pcontext: Context
  pcszw: Size
  pd: PD
  pdc: PDC
  pdl: PDL
  pfs: PFS
  phr: HResult
  phresults: HResults
  pid: PID
  piid: IIDs
  pkt: Packet
  pnp: PnP
  pol: Policy
  posix: POSIX
  pptp: PPTP
  pr: PR
  prefered: Preferred
  preq: EQ
  prge: GE
  prgszw: Data
  prgt: GT
  pri: P  
  prle: LE
  prlt: LT
  prne: NE
  prop2: Property2
  prop: Property
  props3: Properties3
  props: Properties
  prot: Protocol
  prt: Partition
  psid: SID
  psk: PSK
  ptb1: Buffer1
  ptp: PTP
  ptr: Pointer
  pub: Publisher
  puuid: UUID
  pvolid: Volume
  pw: Password
  qm: QM
  qmid: QMID
  qmqm: QMQM
  qos: QoS
  qtn: QTN
  qtype: QTYPE
  quar: Quarantine
  raid5: RAID5
  raid: RAID
  raids: RAID5
  rdn: RDN
  rdns: RDNs
  rec: Record
  recs: Records
  rectl: Rectangle
  ref: Reference
  refipid: REFIPID
  refr: Refresher
  refs: References
  rel: Relation
  relop: Op
  rem: Remote
  repl: Replication
  req: Request
  res: Restriction
  resp: Response
  responce: Response
  resultw: Result
  ret: Return
  rfc822: RFC822
  rfc: RFC
  rgb: Data
  rid: RID
  rids: RIDs
  riid: IID
  ripid: IPID
  rma: RMA
  rmt: Remote
  rot: ROT
  rp: RP
  rpc: RPC
  rpl: Replication
  rr: RR
  rrl: RRL
  rrp: RRP
  rrsig: RRSIG
  rrtype: Type
  rsop: RSOP
  rt: RT
  rtqm: RTQM
  rua: RUA
  rw: RW
  s4u: S4U
  sa: SA
  sacl: SACL
  sam2: SAM2
  sam4: SAM4
  sam: SAM
  san: SAN
  sas: SAS
  sata: SATA
  sbz1: SBZ1
  sbz2: SBZ2
  scm2: SCM2
  scm: SCM
  scsi: SCSI
  scv: Scavenging
  sd: SD
  sddl: SDDL
  sdp: SDP
  sec: Security
  sha1: SHA1
  sha256: SHA256
  sha384: SHA384
  sid: SID
  sids: SIDs
  skd: SKD
  sku: SKU
  smb: SMB
  smbs: SMBs
  smtp: SMTP
  soa: SOA
  soh: SOH
  spd: SPD # special properties data
  spn: SPN
  src: Source
  srce: Source
  srp: SRP
  srv: Server
  ssa: SSA
  ssd: SSD
  ssl: SSL
  sso: SSO
  stg: Storage
  str: String
  succ: Success
  svc: Service
  svcs: Services
  svr: Server
  symm: Symmetric
  sys: System
  tapi: TAPI
  tc: TC
  tcp: TCP
  tcpip: TCPIP
  tdl: TDL
  tdo: TDO
  term: Terminate
  thd: Thread
  thds: Threads
  tid: TID
  tls: TLS
  tlsa: TLSA
  tm: TM
  tod: ToD
  trig: Trigger
  ts: TS
  tsid: TSID # transmitting-subscriber id
  tt: TT
  ttl: TTL
  twr: Tower
  txt: text
  typ: Type
  u: Union
  uas: UAS
  udf: UDF
  udp: UDP
  ui1: UI1
  ui2: UI2
  ui4: UI4
  ui8: UI8
  ui: UI
  uid: UID
  uint128: Uint128
  uint16: Uint16
  uint32: Uint32
  uint64: Uint64
  uint8: Uint8
  uint: Uint
  ulong: Uint32
  unc: UNC
  unk: Unknown
  uow: UOW
  upd: Update
  upgrad: Upgrade
  upn: UPN
  ureply: Reply
  uri: URI
  url: URL
  usb: USB
  utf8: UTF8
  uuid: UUID
  v6: V6
  val: Value
  vcs: VCS
  vds: VDS
  vec: Vector
  vffffffff: VQ
  vft: VFT
  vpd: VPD
  vq: VQ
  vss: VSS
  vt: VT
  vtable: VTable
  vti1: I1
  vti2: I2
  vti4: I4
  vti8: I8
  vtr4: R4
  vtr8: R8
  vtui1: UI1
  vtui2: UI2
  vtui4: UI4
  vtui8: UI8
  w2k: W2K
  wan: WAN
  wbem: WBEM
  wco: WCO
  wfd: WFD
  win2k3: WIN2K3
  wins: WINS
  wks: WKS
  wksta: Workstation
  wow64: WOW64
  wow64a: WOW64A
  wow64w: WOW64W
  wow: WOW
  wwn: WWN
  xact: Transaction
  xfr: XFR
  xml: XML
  xpress: XPress
  rms: RMS
  html: HTML
  dhtml: DHTML
  cc: CC
  bcc: BCC
  timeou: Timeout
  md: MD
  base2w: Base2W
  base3w: Base3W
  wam: WAM
  ims: IMS
  bstrguid: GUID
  ccw: CCW
  ocsp: OCSP
  sql: SQL
  dsn: DSN
  saf: SAF
  pch: PCH
  parms: Parameters
  msz: Multistring
  sz: String
  sz1: String1
  sz2: String2
  atrs: Attributes
  io: IO
  pci: PCI
  fmt: Format
  mnt: Mount
  dvd: DVD
  ntms: NTMS
  reqd: Required
  nr: NR
  ncs: NCs
  sans: SANs
  dcs: DCs
  usn: USN
  w2k3: W2K3
  win2k: Win2K
  dtnet: NET
  fpo: FPO
  dnssec: DNSSEC
  dbase: Database
  nbstat: NBSTAT
  skwansec: SKWANSEC
