rename:
  P_rdtDeviceType: [RAS, Device, Type]
  RI_rdtDeviceType: [RAS, Device, Type]
  pvarReturn: [Result]
  pUnkCP: [Connection, Point]
  ppCP: [Connection, Point]
  ITransaction: [ITransaction]
  pIIDs: [IIDs]
  ppdsaOrBindings: [Object, Resolver, Bindings]
  pActProperties: [Act, Properties, In]
  ppActProperties: [Act, Properties, Out]
  llVal: [Long, Long, Value]
  lVal: [Long]
  bVal: [Byte]
  iVal: [Short]
  fltVal: [Float]
  dblVal: [Double]
  boolVal: [Bool]
  scode: [H, Result]
  cyVal: [Currency]
  date: [Date]
  bstrVal: [BSTR]
  punkVal: [IUnknown]
  pdispVal: [IDispatch]
  parray: [Safe, Array]
  brecVal: [Brecord]
  pbVal: [Byte, Ptr]
  piVal: [Short, Ptr]
  plVal: [Long, Ptr]
  pllVal: [Long, Long, Ptr]
  pfltVal: [Float, Ptr]
  pdblVal: [Double, Ptr]
  pboolVal: [Bool, Ptr]
  pscode: [HResult, Ptr]
  pcyVal: [Currency, Ptr]
  pdate: [Date, Ptr]
  pbstrVal: [BSTR, Ptr]
  ppunkVal: [IUnknown, Ptr]
  ppdispVal: [IDispatch, Ptr]
  pparray: [Safe, Array, Ptr]
  pvarVal: [Variant, Ptr]
  pvarHandle: [Handle]
  pq: [Queue]
  cVal: [Char]
  pvarRet: [Result]
  VARENUM: [Var, Enum]
  uiVal: [Ushort]
  ulVal: [Ulong]
  ullVal: [Ulong, Long]
  intVal: [Int]
  uintVal: [Uint]
  decVal: [Decimal]
  pcVal: [Char, Ptr]
  puiVal: [Ushort, Ptr]
  pulVal: [Ulong, Ptr]
  pullVal: [Ulong, Long, Ptr]
  pintVal: [Int, Ptr]
  puintVal: [Uint, Ptr]
  pdecVal: [Decimal, Ptr]
  iTInfo: [Type, Info, Index]
