lookBehind:
  h:
    context: [context]
    connection: [connection]
    interface: [interface]
    sc: [service]
    event: [event]
    dim: [h]
    ras: [h]
    port: [port]
    service: [service]
    spl: [spl]
    xcv: [xcv]
    wnd: [wnd]
    query: [query]
    rpc: [h]
    handle: [handle]
    printer: [printer]
    notification: [notification]
    proxy: [proxy]
    remote: [remote]
    queue: [queue]
    cursor: [cursor]
    val: [large, integer]
    client: [client]
    enum: [enum]
    policy: [policy]
    object: [object]
    notify: [notify]
    net: [net]
    host: [host]
    cluster: [cluster]
    group: [group]
    network: [network]
    node: [node]
    depends: [depdends]
    resource: [resource]
    batch: [batch]
    ref: [ref, h] # 1-st step
    type: [type, handle] # 2-nd step
    key: [key]
    result: [hresult]
    drs: [drs, handle]
    ctx: [ctx]
    card: [card]
