split:
  #vt: [var, type]
  acceptdownlevelapis: [accept, down, level, apis]
  acol: [columns]
  actionsa: [actions, a]
  actionsw: [actions, w]
  actvflags: [activate, flags]
  acvr: [cert, view, restrictions]
  acxh: [async, session]
  addclonedcreply: [add, clone, dc, reply]
  addclonedcreq: [add, clone, dc, req]
  addentry: [add, entry]
  addentryreply: [add, entry, reply]
  addentryreq: [add, entry, req]
  addrarray: [addr, array]
  addsidreply: [add, sid, history, reply]
  addsidreq: [add, sid, history, req]
  addversmap: [add, vers, map]
  addvolumeplex: [add, volume, plex]
  advanceddisk: [advanced, disk]
  advfeatureflags: [adv, feature, flags]
  aesgcm128: [aes, gcm128]
  aesgcm192: [aes, gcm192]
  aesgcm256: [aes, gcm256]
  aesgmac128: [aes, gmac128]
  aesgmac192: [aes, gmac192]
  aesgmac256: [aes, gmac256]
  alertschedule: [alert, schedule]
  anndelta: [announce, delta]
  arraydesc: [array, desc]
  atrerr: [attribute, err]
  attrblock: [attr, block]
  attrval: [attr, val]
  attrvalblock: [attr, val, block]
  authip: [auth, ip]
  autoconfigure: [auto, configure]
  autostart: [auto, start]
  avresponse: [avg, response]
  bela: [backup, event, log, a]
  belw: [backup, event, log, w]
  bigbufneed: [big, buffer, need]
  bmr: [bit, mask, restriction]
  bootindicator: [boot, indicator]
  bootloader: [boot, loader]
  breakvolumeplex: [break, volume, plex]
  bustype: [bus, type]
  bvp: [break, volume, plex]
  bytesrcvd: [bytes, received]
  bytessent: [bytes, sent]
  caclsid: [class, id, array]
  cainfo: [ca, info]
  callconv: [call, conv]
  calpwstr: [unicode, string, array]
  capropvar: [prop, variant, array]
  capropvariant: [prop, variant, array]
  catransprop: [ca, transport, prop]
  caub: [byte, array]
  cauh: [ularge, integer, array]
  caui: [ushort, array]
  caul: [ulong, array]
  cauuid: [Uuid, array]
  cbrow: [cb, row]
  ccol: [columns, count]
  ccvr: [c, cert, view, restriction]
  certtransblob: [cert, transport, blob]
  certtransdbattribute: [cert, trans, db, attribute]
  certtransdbcolumn: [cert, trans, db, column]
  certtransdbextension: [cert, trans, db, extension]
  certtransdbresultcolumn: [cert, trans, db, result, column]
  certtransdbresultrow: [cert, trans, db, result, row]
  certsvc: [cert, svc]
  certtype: [cert, type]
  certviewrestriction: [cert, view, restriction]
  chglog: [change, log]
  clonedcreply: [clone, dc, reply]
  clonedcreq: [clone, dc, req]
  clsctx: [class, ctx]
  clsid: [class, id]
  cltype: [client, type]
  clusprep: [cluster, prepare]
  cname: [client, name]
  computername: [computer, name]
  comversion: [com, version]
  config2a: [config, 2a]
  config2w: [config, 2ww]
  configa: [config, a]
  configurationw: [config, w]
  configw: [config, w]
  contref: [continuation, referral]
  coserverinfo: [com, server, info]
  coverpage: [cover, page]
  cp: [create, partition]
  cpid: [code, page, id]
  crackreply: [crack, names, reply]
  crackreq: [crack, names, req]
  crashdump: [crash, dump]
  createcursor: [create, cursor]
  createlun: [create, lun]
  createpartition: [create, partition]
  createvolume: [create, volume]
  custdata: [custom, data]
  custdataitem: [custom, data, item]
  cv: [create, volume]
  cvd: [create, v, disk]
  cxh: [session]
  dal: [address, list]
  dataelement: [data, element]
  datatype: [data, type]
  datatypes: [data, types]
  dcinforeply: [dc, info, reply]
  dcinforeq: [dc, info, req]
  dd: [device, descriptor]
  demotionreply: [demotion, reply]
  demotionreq: [demotion, req]
  desckind: [desc, kind]
  descriptiona: [description, a]
  descriptionw: [description, w]
  devmode: [dev, mode]
  devopens: [device, opens]
  dflags: [disk, flags]
  dg: [disk, group]
  dgid: [disk, group, id]
  dhcpbootp: [dhcp, bootp]
  dhcpd: [dhcp, d]
  dhcpip: [dhcp, ip]
  dhcpipv6: [dhcp, ipv6]
  dhcpm: [dhcp, m]
  dhcpsrv: [dhcp, srv]
  dhcpsrv: [dhcp, srv]
  dih: [device, id, header]
  direrr: [directory, err]
  diskid: [disk, id]
  diskspacethreshold: [disk, space, threshold]
  dispid: [dispatch, id]
  dispparams: [disp, params]
  dlflags: [drive, letter, flags]
  dmnotify: [dm, notify]
  dmprogress: [dm, progress]
  dnskeys: [dns, keys]
  dnssrv: [dns, srv]
  domainname: [domain, name]
  dsname: [ds, name]
  dsrole: [ds, role]
  dualstringarray: [dual, string, array]
  eea: [ansi]
  eeu: [unicode]
  el: [event, log]
  ela: [event, log, a]
  elapsedt: [elapsed, time]
  elemdesc: [elem, desc]
  elfa: [event, log, a]
  elfw: [event, log, w]
  elw: [event, log, w]
  enablefcbopens: [enable, fcb, opens]
  enableforcedlogoff: [enable, forced, logoff]
  enableoplocks: [enable, op, locks]
  enableraw: [enable, raw]
  enablesharednetdrives: [enable, shared, net, drives]
  enablesoftcompat: [enable, soft, compat]
  encryption3des: ["3", des]
  entinf: [entity, info]
  entinflist: [entity, info, list]
  errorthreshold: [error, threshold]
  excepinfo: [excep, info]
  exfat: [ex, fat]
  existreply: [exist, reply]
  existreq: [exist, req]
  extendvolume: [extend, volume]
  exw: [ex, w]
  faggregatable: [aggregatable]
  fappobject: [app, object]
  fbindable: [bindable]
  fcancreate: [can, create]
  fchain: [f, chain]
  fcontrol: [control]
  fdefault: [default]
  fdefaultbind: [default, bind]
  fdefaultcollelem: [default, coll, elem]
  fdefaultvtable: [default, vtable]
  fdispatchable: [dispatchable]
  fdisplaybind: [display, bind]
  fdual: [dual]
  fhascustdata: [has, cust, data]
  fhasdefault: [has, default]
  fhasdiskimage: [has, disk, image]
  fhidden: [hidden]
  filterid: [filter, id]
  fimmediatebind: [immediate, bind]
  fin: [in]
  fixedsize: [fixed, size]
  flcid: [lcid]
  flicensed: [licensed]
  fnonbrowsable: [non, browsable]
  fnonextensible: [non, extensible]
  foleautomation: [ole, automation]
  fopens: [file, opens]
  fopt: [optional]
  fout: [out]
  fpredeclid: [predecl, id]
  fproxy: [proxy]
  freadonly: [read, only]
  freplaceable: [replaceable]
  frequestedit: [request, edit]
  frestricted: [restricted]
  fretval: [ret, val]
  fsource: [source]
  fuidefault: [ui, default]
  funcdesc: [func, desc]
  funcflags: [func, flags]
  funckind: [func, kind]
  fusegetlasterror: [use, get, last, error]
  gameos: [game, os]
  getchgreply: [get, nc, changes, reply]
  getchgreq: [get, nc, changes, req]
  getmemberships2: [get, memberships2]
  getmemberships2reply: [get, memberships, reply]
  getmemberships2req: [get, memberships2, req]
  getmembershipsreply: [get, memberships, reply]
  getmembershipsreq: [get, memberships, req]
  getreplinfo: [get, replication, info]
  gprsop: [gp, rsop]
  haveiid: [have, iid]
  havevartype: [have, var, type]
  hbaport: [hba, port]
  hibernationfile: [hibernation, file]
  hiperf: [hi, perf]
  hotspare: [hot, spare]
  hquery: [query]
  hreftype: [href, type]
  hwtype: [hw, type]
  icxr: [remote, session]
  idguid: [guid]
  ifile: [installed, file]
  implicitappobj: [implicit, app, obj]
  impltypeflags: [impl, type, flags]
  ineta: [inet, a]
  infoa: [info, a]
  infow: [info, w]
  initconntable: [init, connection, table]
  initfiletable: [init, file, table]
  initsearchtable: [init, search, table]
  initsesstable: [init, session, table]
  initworkitems: [init, work, items]
  inproc: [in, process]
  interfaceid: [interface, id]
  intformprob: [attribute, problem]
  intprob: [attribute, problem]
  invkind: [invoke, kind]
  invokekind: [invoke, kind]
  ipaddress: [ip, address]
  iparray: [ip, array]
  iphttps: [ip, https]
  iptls: [ip, tls]
  irpstacksize: [irp, stack, size]
  jobsqueued: [jobs, queued]
  laddr: [local, addr]
  langroup: [lan, group]
  lanroot: [lan, root]
  lbound: [lower, bound]
  lcid: [locale, id]
  ldmaction: [ldm, action]
  libflags: [lib, flags]
  linkdown: [link, down]
  linkinfovalidtime: [link, info, valid, time]
  lmannounce: [lm, announce]
  lpadesc: [array, desc]
  lptdesc: [type, desc]
  mainmode: [main, module]
  maxcopyreadlen: [max, copy, read, len]
  maxcopywritelen: [max, copy, write, len]
  maxfreeconnections: [max, free, connections]
  maxkeepcomplsearch: [max, keep, compl, search]
  maxkeepsearch: [max, keep, search]
  maxlinkdelay: [max, link, delay]
  maxmpxct: [max, mpx, count]
  maxnonpagedmemoryusage: [max, non, paged, memory, usage]
  maxpagedmemoryusage: [max, paged, memory, usage]
  maxrawbuflen: [max, raw, buf, len]
  maxworkitemidletime: [max, work, item, idle, time]
  maxworkitems: [max, work, items]
  mclient: [madcap, client]
  memid: [member, id]
  minfreeconnections: [min, free, connections]
  minfreeworkitems: [min, free, work, items]
  minkeepcomplsearch: [min, keep, compl, search]
  minkeepsearch: [min, keep, search]
  minlinkthroughput: [min, link, throughput]
  minrcvqueue: [min, receive, queue]
  movereply: [move, reply]
  movereq: [move, req]
  mqcolumnset: [column, set]
  mqpropertyrestriction: [property, restriction]
  mqrestriction: [restriction]
  mqsortkey: [sort, key]
  mqsortset: [sort, set]
  msgrequest: [msg, request]
  namelen: [0name, len]
  nameresop: [0name, resolution, operation]
  namerr: [0name, err]
  ndx: [index]
  needsresync: [needs, resync]
  netname: [network, name]
  netnames: [net, names]
  networkaddress: [network, address]
  networkerrorthreshold: [network, error, threshold]
  noencap: [no, encap]
  noquorum: [no, quorum]
  noserialize: [no, serialize]
  notpresent: [not, present]
  nt4sid: [nt4, sid]
  ntpclient: [ntp, client]
  ntpserver: [ntp, server]
  numberofvcs: [number, of, clients]
  numblockthreads: [num, block, threads]
  objectid: [object, id]
  objref: [obj, ref]
  opensearch: [open, search]
  oplockbreakresponsewait: [op, lock, break, response, wait]
  oplockbreakwait: [op, lock, break, wait]
  orpcthat: [orpc, that]
  orpcthis: [orpc, this]
  osversioninfo: [os, version, info]
  outbuf: [output, buf]
  ovft: [vft]
  pactype: [pac, type]
  pacxh: [async, session]
  pagefile: [page, file]
  paramdesc: [param, desc]
  paramdescex: [param, desc, ex]
  paramflags: [param, flags]
  paramsa: [params, a]
  paramsw: [params, w]
  paramw: [param, w]
  partitionstyle: [partition, style]
  passwordlength: [password, length]
  pathname: [path, name]
  pchannel: [p, channel]
  pclsid: [class, ids]
  pctinfo: [pc, type, info]
  pcxh: [session]
  permerrors: [perm, errors]
  pfsdh1: [pfs, dh1]
  pfsdh2048: [pfs, dh2048]
  pfsdh24: [pfs, dh24]
  pfsdh2: [pfs, dh2]
  pfsecdh256: [pfs, ecdh256]
  pfsecdh384: [pfs, ecdh384]
  picxr: [remote, session]
  playto: [play, to]
  pnotifyobject: [notify, object]
  pnr: [pull, partner]
  pnrs: [pull, partners]
  pparamdescex: [param, desc, ex]
  problemlist: [problem, list]
  processa: [process, a]
  processw: [process, w]
  propertyget: [property, get]
  propertyput: [property, put]
  propertyputref: [property, put, ref]
  propvariant: [prop, variant]
  protseq: [protocol, sequence]
  protseqs: [protocol, sequences]
  prpcremoteobject: [remote, object]
  prval: [value]
  psd: [description]
  psda: [delayed, auto, start]
  psfa: [failure, actions]
  psfaf: [failure, actions, flag]
  pspn: [preferred, node]
  psps: [preshutdown]
  psr: [status, reason]
  psrp: [required, privileges]
  pssid: [sid, info]
  psti: [trigger, info]
  ptunnel: [p, tunnel]
  purevirtual: [pure, virtual]
  pwerrors: [pw, errors]
  qft: [queue, format, type]
  qi: [query, interface]
  quarconfigrequest: [quar, config, request]
  quarenc: [quar, enc]
  quarrequest: [quar, request]
  querysitesreply: [query, sites, reply]
  querysitesreplyelement: [query, sites, reply, element]
  querysitesreq: [query, sites, req]
  raddr: [remote, addr]
  rawworkitems: [raw, work, items]
  readngckeyreply: [read, ngc, key, reply]
  readngckeyreq: [read, ngc, key, req]
  recordset: [record, set]
  recoverpack: [recover, pack]
  refcount: [ref, count]
  referr: [referral, err]
  regionstatus: [region, status]
  regiontype: [region, type]
  reminterfaceref: [rem, interface, ref]
  remotereadack: [remote, read, ack]
  remotereaddesc2: [remote, read, desc2]
  remotereaddesc: [remote, read, desc]
  removevolumeplex: [remove, volume, plex]
  remqiresult: [rem, query, interface, result]
  repadd: [add, replica]
  repairvolumeplex: [repair, volume, plex]
  repdel: [del, replica]
  replacedisk: [replace, disk]
  replentinflist: [replication, entity, info, list]
  repltimes: [replication, times]
  replvalinf: [replication, value, info]
  repmod: [modify, replica]
  repsync: [replica, sync]
  repverifyobj: [verify, reply, obj]
  reqbufneed: [req, buffer, need]
  reqstatus: [req, status]
  revmemb: [reverse, membership]
  rflags: [region, flags]
  rgbounds: [rg, bounds]
  rgsabound: [rgsa, bound]
  rgvarg: [args]
  rmdmnreply: [remove, ds, domain, reply]
  rmdmnreq: [remove, ds, domain, req]
  rmsvrreply: [remove, server, reply]
  rmsvrreq: [remove, server, req]
  rmtntfy: [remote, notify]
  ro: [read, only]
  rodc: [read, only, dc]
  rowid: [row, id]
  rpcep: [rpc, ep]
  rulea: [rule, a]
  rulew: [rule, w]
  rvalent: [val, entry]
  safearr: [safe, array]
  safearray: [safe, array]
  safearraybound: [safe, array, bound]
  safearrayunion: [safe, array, union]
  scavqosinfoupdatetime: [scav, qos, info, update, time]
  scavtimeout: [scav, timeout]
  secerr: [sec, err]
  secpkg: [security, package]
  securitydescriptor: [security, descriptor]
  serrorout: [sess, errors]
  serverbuff: [server, buffer]
  sessconns: [session, connections]
  sessopens: [session, opens]
  sessusers: [session, users]
  sessvcs: [session, svcs]
  shkey: [sh, key]
  shrinkvolume: [shrink, volume]
  signcert: [sign, cert]
  sitelist: [site, list]
  sitename: [site, name]
  sizedarr: [sized, array]
  sizreqbuf: [size, req, buf]
  sopens: [sess, opens]
  sortascend: [sort, ascend]
  sortdescend: [sort, descend]
  splclient: [client]
  spnreply: [write, spn, reply]
  spnreq: [write, spn, req]
  sstring: [s, string]
  statusa: [status, a]
  statusw: [status, w]
  stdobjref: [std, obj, ref]
  stimedout: [sess, timeouts]
  sv: [shrink, volume]
  svcerr: [svc, err]
  syserr: [sys, err]
  syserrors: [sys, errors]
  sysflag: [sys, flag]
  syskind: [sys, kind]
  systemos: [system, os]
  systemtime: [system, time]
  tcpcdp: [tcp, cdp]
  tdesc: [type, desc]
  tflag: [task, flag]
  threadcountadd: [thread, count, add]
  threadpool: [thread, pool]
  threadpriority: [thread, priority]
  timesource: [time, source]
  tinfo: [task, info]
  tlibattr: [type, lib, attr]
  totsize: [total, size]
  transportaddress: [transport, address]
  transportaddresslength: [transport, address, length]
  transportname: [transport, name]
  trippledes: ["3", des]
  trustanchor: [trust, anchor]
  trustpoint: [trust, point]
  tsendpointinfo: [endpoint, info]
  typeattr: [type, attr]
  typecomp: [type, comp]
  typedesc: [type, desc]
  typeflags: [type, flags]
  typeid: [type, id]
  typekind: [type, kind]
  uname: [user, name]
  upderr: [upd, err]
  updrefs: [update, refs]
  uptodate: [up, to, date]
  usecount: [use, count]
  userpath: [user, path]
  valuelen: [value, length]
  valuename: [value, name]
  valueptr: [value, ptr]
  vardesc: [var, desc]
  varenum: [var, enum]
  varflags: [var, flags]
  varkind: [var, kind]
  vd: [v, disk]
  vdisk: [v, disk]
  verifyreply: [verify, reply]
  verifyreq: [verify, req]
  versioncaps: [version, caps]
  vflags: [volume, flags]
  virtualdisk: [virtual, disk]
  volumelayout: [volume, layout]
  volumestatus: [volume, status]
  volumetype: [volume, type]
  wbemstatus: [status]
  wfdkm: [wfd, km]
  winmgmt: [win, mgmt]
  writengckeyreply: [write, ngc, key, reply]
  writengckeyreq: [write, ngc, key, req]
  xactmemsize: [exact, mem, size]
  xactuow: [xact, uow]
  xfersyntax: [transfer, syntax]
  formattext: [format, text]
  getall: [get, all]
  iiis: [i, iis]
  iwam: [i, wam]
  retval: [ret, val]
  iocsp: [i, ocsp]
  excludeapis: [exclude, apis]
  includeapis: [include, apis]
  logapinames: [log, api, names]
  logfilenames: [log, file, names]
  logrecursively: [log, recursively]
  excludemodules: [exclude, modules]
  includemodules: [include, modules]
  filename: [file, name]
  ipch: [i, pch]
  isaf: [i, saf]
  ira: [i, remote, assistance]
  helpsvc: [help, svc]
  remoteconnectionparms: [remote, connection, params]
  remoteusersessioninfo: [remote, user, session, info]
  sessionid: [session, id]
  sessionstate: [session, state]
  exepath: [exe, path]
  username: [user, name]
  scard: [smart, card]
  redir: [reader]
  scardcontext: [smart, card, context]
  scardhandle: [smart, card, handle]
  fstype: [fs, type]
  devicetype: [device, type]
  deviceattr: [device, attr]
  systemdir: [system, dir]
  rdonly: [read, only]
  nosig: [no, sig]
