trim:
  prefix:
  #- var
  - Api
  - Bstr # ??
  - C
  - CAC
  - E
  - EE
  - G
  - I
  - M
  - R
  - Rpc
  - SA
  - USN
  - Usn # ??
  - a
  - ab
  - adroid
  - aip
  - ap
  - api
  - apl
  - ar
  - as
  - aul
  - avolid
  - b
  - bi
  - bstr
  - c
  - cb
  - cc
  - ch
  - coni1
  - dm
  - dm
  - droid
  - drs
  - dstime
  - dt
  - dw
  - dwl
  - dwp
  - dwsa
  - e
  - eecnp
  - eepti
  - f
  - fadf
  - fdw
  - fi2
  - fi3
  - fl
  - ft
  - ftime
  - grbit
  - guid
  - hr
  - i
  - i64
  - ifd
  - il
  - ipp
  - k
  - l
  - ldm
  - ldw
  - li
  - lp
  - lpb
  - lpc
  - lpcb
  - lpcwstr
  - lpcwsz
  - lpdw
  - lpdwl
  - lpft
  - lplp
  - lplpwsz
  - lpn
  - lpp
  - lppsz
  - lpsa
  - lpstr
  - lpsz
  - lpvalue
  - lpvar
  - lpw
  - lpwcs
  - lpwstr
  - lpwsz
  - m
  - mcid
  - msgi0
  - msgi1
  - n
  - name
  - netlog1
  - netlog2
  - netlog3
  - netlog4
  - netlogon
  - nl
  - nlpr
  - num
  - o
  - obwsz
  - p
  - pa
  - padw
  - pawsz
  - pb
  - pbstr
  - pcch
  - pcelt
  - pcms
  - pctb
  - pcwc
  - pdroid
  - pdsa
  - pdw
  - pext
  - pf
  - pfl
  - pguid
  - ph
  - pipid
  - pl
  - pli
  - pmcid
  - pmsg
  - pmtx
  - pn
  - pp
  - ppb
  - ppdsa
  - ppext
  - ppguid
  - pph
  - ppsz
  - ppv
  - ppwcs
  - ppwsz
  - ppwszz
  - prg
  - prgb
  - pstr
  - pswz
  - psz
  - pszz
  - ptb1
  - ptsz
  - pu
  - pul
  - punk
  - puuid
  - pv
  - pvolid
  - pw
  - pwc
  - pwcs
  - pws
  - pwsz
  - qw
  - r
  - ref
  - refid
  - rel
  - res
  - rg
  - rgb
  - rgch
  - rgdispid
  - rgdispsid
  - rgdroid
  - rgobjid
  - rgsa
  - rgsz
  - rguch
  - rgul
  - rgw
  - rp
  - rpc
  - rpwsz
  - rt
  - s
  - sa
  - sampr
  - samr
  - sesi0
  - sesi1
  - sesi10
  - sesi2
  - sesi502
  - sf
  - shi1005
  - shi1006
  - shi1501
  - shi0
  - shi1
  - shi2
  - shi501
  - shi502
  - shi503
  - srvai0
  - st
  - str
  - sts0
  - sv100
  - sv1005
  - sv101
  - sv1010
  - sv1016
  - sv1017
  - sv1018
  - sv102
  - sv102
  - sv103
  - sv1107
  - sv1501
  - sv1502
  - sv1503
  - sv1506
  - sv1510
  - sv1511
  - sv1512
  - sv1513
  - sv1514
  - sv1515
  - sv1516
  - sv1518
  - sv1523
  - sv1528
  - sv1529
  - sv1530
  - sv1533
  - sv1534
  - sv1535
  - sv1536
  - sv1538
  - sv1539
  - sv1540
  - sv1541
  - sv1542
  - sv1543
  - sv1544
  - sv1545
  - sv1546
  - sv1547
  - sv1548
  - sv1549
  - sv1550
  - sv1551
  - sv1552
  - sv1553
  - sv1554
  - sv1555
  - sv1556
  - sv502
  - sv503
  - sv599
  - svti0
  - svti1
  - svti2
  - svti3
  - sz
  - tkind
  - tm
  - tod
  - tp
  - ts
  - tsg
  - tsz
  - u
  - u64
  - ui0
  - ui1
  - ui2
  - ui3
  - ul
  - ull
  - us
  - usn
  - usnvec
  - usrlog1
  - uuid
  - ve
  - w
  - wc
  - wki100
  - wki101
  - wki1013
  - wki1018
  - wki102
  - wki1046
  - wki502
  - wkti0
  - wkui0
  - wkui1
  - wsz
  - wwn
  - pmdhi
  - piadmbw
  - pla
  - pch
  - fpv
  - fpb
  - fmsz
  - msz
  - sz
  - io
  - pio
