// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package wdsrpcinterface

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
)

// WdsRpcInterface server interface.
type InterfaceServer interface {

	// The WdsRpcMessage (opnum 0) method sends the request packet to the server and returns
	// the corresponding reply packet.
	//
	// Return Values: The method MUST return ERROR_SUCCESS (0x00000000) on success or a
	// non-zero Win32 error code value if an error occurred.
	Message(context.Context, *MessageRequest) (*MessageResponse, error)
}

func RegisterInterfaceServer(conn dcerpc.Conn, o InterfaceServer, opts ...dcerpc.Option) {
	conn.RegisterServer(NewInterfaceServerHandle(o), append(opts, dcerpc.WithAbstractSyntax(InterfaceSyntaxV1_0))...)
}

func NewInterfaceServerHandle(o InterfaceServer) dcerpc.ServerHandle {
	return func(ctx context.Context, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
		return InterfaceServerHandle(ctx, o, opNum, r)
	}
}

func InterfaceServerHandle(ctx context.Context, o InterfaceServer, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
	switch opNum {
	case 0: // WdsRpcMessage
		op := &xxx_MessageOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &MessageRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.Message(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	}
	return nil, nil
}

// Unimplemented WdsRpcInterface
type UnimplementedInterfaceServer struct {
}

func (UnimplementedInterfaceServer) Message(context.Context, *MessageRequest) (*MessageResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}

var _ InterfaceServer = (*UnimplementedInterfaceServer)(nil)
