// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package iclusterlogex3

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	dcom "github.com/oiweiwei/go-msrpc/msrpc/dcom"
	csvp "github.com/oiweiwei/go-msrpc/msrpc/dcom/csvp"
	iclusterlogex2 "github.com/oiweiwei/go-msrpc/msrpc/dcom/csvp/iclusterlogex2/v0"
	oaut "github.com/oiweiwei/go-msrpc/msrpc/dcom/oaut"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = dcom.GoPackage
	_ = iclusterlogex2.GoPackage
	_ = csvp.GoPackage
	_ = oaut.GoPackage
)

var (
	// import guard
	GoPackage = "dcom/csvp"
)

var (
	// IClusterLogEx3 interface identifier e6d3c166-560f-4b58-b31a-fdea05fb606f
	ClusterLogEx3IID = &dcom.IID{Data1: 0xe6d3c166, Data2: 0x560f, Data3: 0x4b58, Data4: []byte{0xb3, 0x1a, 0xfd, 0xea, 0x05, 0xfb, 0x60, 0x6f}}
	// Syntax UUID
	ClusterLogEx3SyntaxUUID = &uuid.UUID{TimeLow: 0xe6d3c166, TimeMid: 0x560f, TimeHiAndVersion: 0x4b58, ClockSeqHiAndReserved: 0xb3, ClockSeqLow: 0x1a, Node: [6]uint8{0xfd, 0xea, 0x5, 0xfb, 0x60, 0x6f}}
	// Syntax ID
	ClusterLogEx3SyntaxV0_0 = &dcerpc.SyntaxID{IfUUID: ClusterLogEx3SyntaxUUID, IfVersionMajor: 0, IfVersionMinor: 0}
)

// IClusterLogEx3 interface.
type ClusterLogEx3Client interface {

	// IClusterLogEx2 retrieval method.
	ClusterLogEx2() iclusterlogex2.ClusterLogEx2Client

	// The GenerateLogEx2 method<57> writes a file that contains diagnostic information
	// about failover clusters for the server on which it executes. The content and format
	// of the file are implementation-specific but SHOULD contain diagnostic information.
	//
	// Return Values: A signed 32-bit value that indicates return status. If the method
	// returns a negative value, it has failed. Zero or positive values indicate success,
	// with the lower 16 bits in positive nonzero values containing warnings or flags defined
	// in the method implementation. For more information about Microsoft Win32 error codes
	// and HRESULT values, see [MS-ERREF] section 2.2 and 2.1.
	//
	//	+-------------------+--------------------------+
	//	|      RETURN       |                          |
	//	|    VALUE/CODE     |       DESCRIPTION        |
	//	|                   |                          |
	//	+-------------------+--------------------------+
	//	+-------------------+--------------------------+
	//	| 0x00000000 S_OK   | The call was successful. |
	//	+-------------------+--------------------------+
	//
	// For any other condition, this method MUST return a value that is not one of the values
	// listed in the preceding table. The client MUST behave in an identical manner for
	// all return values not listed in the preceding table.
	//
	// Exceptions Thrown: No exceptions are thrown beyond those thrown by the underlying
	// RPC protocol [MS-RPCE].
	//
	// The opnum field value for this method is 9.
	GenerateLogEx2(context.Context, *GenerateLogEx2Request, ...dcerpc.CallOption) (*GenerateLogEx2Response, error)

	// AlterContext alters the client context.
	AlterContext(context.Context, ...dcerpc.Option) error

	// Conn returns the client connection (unsafe)
	Conn() dcerpc.Conn

	// IPID sets the object interface identifier.
	IPID(context.Context, *dcom.IPID) ClusterLogEx3Client
}

type xxx_DefaultClusterLogEx3Client struct {
	iclusterlogex2.ClusterLogEx2Client
	cc   dcerpc.Conn
	ipid *dcom.IPID
}

func (o *xxx_DefaultClusterLogEx3Client) ClusterLogEx2() iclusterlogex2.ClusterLogEx2Client {
	return o.ClusterLogEx2Client
}

func (o *xxx_DefaultClusterLogEx3Client) GenerateLogEx2(ctx context.Context, in *GenerateLogEx2Request, opts ...dcerpc.CallOption) (*GenerateLogEx2Response, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &GenerateLogEx2Response{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultClusterLogEx3Client) AlterContext(ctx context.Context, opts ...dcerpc.Option) error {
	return o.cc.AlterContext(ctx, opts...)
}

func (o *xxx_DefaultClusterLogEx3Client) Conn() dcerpc.Conn {
	return o.cc
}

func (o *xxx_DefaultClusterLogEx3Client) IPID(ctx context.Context, ipid *dcom.IPID) ClusterLogEx3Client {
	if ipid == nil {
		ipid = &dcom.IPID{}
	}
	return &xxx_DefaultClusterLogEx3Client{
		ClusterLogEx2Client: o.ClusterLogEx2Client.IPID(ctx, ipid),
		cc:                  o.cc,
		ipid:                ipid,
	}
}

func NewClusterLogEx3Client(ctx context.Context, cc dcerpc.Conn, opts ...dcerpc.Option) (ClusterLogEx3Client, error) {
	var err error
	if !dcom.IsSuperclass(opts) {
		cc, err = cc.Bind(ctx, append(opts, dcerpc.WithAbstractSyntax(ClusterLogEx3SyntaxV0_0))...)
		if err != nil {
			return nil, err
		}
	}
	base, err := iclusterlogex2.NewClusterLogEx2Client(ctx, cc, append(opts, dcom.Superclass(cc))...)
	if err != nil {
		return nil, err
	}
	ipid, ok := dcom.HasIPID(opts)
	if ok {
		base = base.IPID(ctx, ipid)
	}
	return &xxx_DefaultClusterLogEx3Client{
		ClusterLogEx2Client: base,
		cc:                  cc,
		ipid:                ipid,
	}, nil
}

// xxx_GenerateLogEx2Operation structure represents the GenerateLogEx2 operation
type xxx_GenerateLogEx2Operation struct {
	This                           *dcom.ORPCThis        `idl:"name:This" json:"this"`
	That                           *dcom.ORPCThat        `idl:"name:That" json:"that"`
	Type                           csvp.ClusterLogType   `idl:"name:Type" json:"type"`
	SpanMinutes                    uint32                `idl:"name:SpanMinutes" json:"span_minutes"`
	Flags                          csvp.ClusterLogExFlag `idl:"name:flags" json:"flags"`
	LongFilePath                   *oaut.String          `idl:"name:LongFilePath" json:"long_file_path"`
	NoCollate                      bool                  `idl:"name:NoCollate" json:"no_collate"`
	SemicolonSeperatedLogFilesPath *oaut.String          `idl:"name:SemicolonSeperatedLogFilesPath" json:"semicolon_seperated_log_files_path"`
	Return                         int32                 `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of GenerateLogEx2 operation.
func (o *xxx_GenerateLogEx2Operation) OpNum() int { return 12 }

// OpName returns the operation name of GenerateLogEx2 operation.
func (o *xxx_GenerateLogEx2Operation) OpName() string { return "/IClusterLogEx3/v0/GenerateLogEx2" }

func (o *xxx_GenerateLogEx2Operation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GenerateLogEx2Operation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Type {in} (1:{alias=ClusterLogType}(enum))
	{
		if err := w.WriteEnum(uint16(o.Type)); err != nil {
			return err
		}
	}
	// SpanMinutes {in} (1:{alias=ULONG}(uint32))
	{
		if err := w.WriteData(o.SpanMinutes); err != nil {
			return err
		}
	}
	// flags {in} (1:{alias=ClusterLogExFlag}(enum))
	{
		if err := w.WriteEnum(uint16(o.Flags)); err != nil {
			return err
		}
	}
	// NoCollate {in} (1:{alias=BOOL}(int32))
	{
		if !o.NoCollate {
			if err := w.WriteData(int32(0)); err != nil {
				return err
			}
		} else {
			if err := w.WriteData(int32(1)); err != nil {
				return err
			}
		}
	}
	return nil
}

func (o *xxx_GenerateLogEx2Operation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Type {in} (1:{alias=ClusterLogType}(enum))
	{
		if err := w.ReadEnum((*uint16)(&o.Type)); err != nil {
			return err
		}
	}
	// SpanMinutes {in} (1:{alias=ULONG}(uint32))
	{
		if err := w.ReadData(&o.SpanMinutes); err != nil {
			return err
		}
	}
	// flags {in} (1:{alias=ClusterLogExFlag}(enum))
	{
		if err := w.ReadEnum((*uint16)(&o.Flags)); err != nil {
			return err
		}
	}
	// NoCollate {in} (1:{alias=BOOL}(int32))
	{
		var _bNoCollate int32
		if err := w.ReadData(&_bNoCollate); err != nil {
			return err
		}
		o.NoCollate = _bNoCollate != 0
	}
	return nil
}

func (o *xxx_GenerateLogEx2Operation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GenerateLogEx2Operation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// LongFilePath {out} (1:{pointer=ref}*(2))(2:{pointer=unique, alias=BSTR}*(1))(3:{pointer=unique, alias=_BSTR, names=FLAGGED_WORD_BLOB}(struct))
	{
		if o.LongFilePath != nil {
			_ptr_LongFilePath := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				if o.LongFilePath != nil {
					if err := o.LongFilePath.MarshalNDR(ctx, w); err != nil {
						return err
					}
				} else {
					if err := (&oaut.String{}).MarshalNDR(ctx, w); err != nil {
						return err
					}
				}
				return nil
			})
			if err := w.WritePointer(&o.LongFilePath, _ptr_LongFilePath); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// SemicolonSeperatedLogFilesPath {out} (1:{pointer=ref}*(2))(2:{pointer=unique, alias=BSTR}*(1))(3:{pointer=unique, alias=_BSTR, names=FLAGGED_WORD_BLOB}(struct))
	{
		if o.SemicolonSeperatedLogFilesPath != nil {
			_ptr_SemicolonSeperatedLogFilesPath := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				if o.SemicolonSeperatedLogFilesPath != nil {
					if err := o.SemicolonSeperatedLogFilesPath.MarshalNDR(ctx, w); err != nil {
						return err
					}
				} else {
					if err := (&oaut.String{}).MarshalNDR(ctx, w); err != nil {
						return err
					}
				}
				return nil
			})
			if err := w.WritePointer(&o.SemicolonSeperatedLogFilesPath, _ptr_SemicolonSeperatedLogFilesPath); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GenerateLogEx2Operation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// LongFilePath {out} (1:{pointer=ref}*(2))(2:{pointer=unique, alias=BSTR}*(1))(3:{pointer=unique, alias=_BSTR, names=FLAGGED_WORD_BLOB}(struct))
	{
		_ptr_LongFilePath := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if o.LongFilePath == nil {
				o.LongFilePath = &oaut.String{}
			}
			if err := o.LongFilePath.UnmarshalNDR(ctx, w); err != nil {
				return err
			}
			return nil
		})
		_s_LongFilePath := func(ptr interface{}) { o.LongFilePath = *ptr.(**oaut.String) }
		if err := w.ReadPointer(&o.LongFilePath, _s_LongFilePath, _ptr_LongFilePath); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// SemicolonSeperatedLogFilesPath {out} (1:{pointer=ref}*(2))(2:{pointer=unique, alias=BSTR}*(1))(3:{pointer=unique, alias=_BSTR, names=FLAGGED_WORD_BLOB}(struct))
	{
		_ptr_SemicolonSeperatedLogFilesPath := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if o.SemicolonSeperatedLogFilesPath == nil {
				o.SemicolonSeperatedLogFilesPath = &oaut.String{}
			}
			if err := o.SemicolonSeperatedLogFilesPath.UnmarshalNDR(ctx, w); err != nil {
				return err
			}
			return nil
		})
		_s_SemicolonSeperatedLogFilesPath := func(ptr interface{}) { o.SemicolonSeperatedLogFilesPath = *ptr.(**oaut.String) }
		if err := w.ReadPointer(&o.SemicolonSeperatedLogFilesPath, _s_SemicolonSeperatedLogFilesPath, _ptr_SemicolonSeperatedLogFilesPath); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// GenerateLogEx2Request structure represents the GenerateLogEx2 operation request
type GenerateLogEx2Request struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This *dcom.ORPCThis `idl:"name:This" json:"this"`
	// Type: Is of type ClusterLogType enum as specified in section 2.2.28.
	Type csvp.ClusterLogType `idl:"name:Type" json:"type"`
	// SpanMinutes: A value, in minutes, that indicates those values that SHOULD be in the
	// log. Events that occurred in the range of Now to (Now – SpanMinutes) MUST be in
	// the log and no others. Now is the GMT on the server.
	SpanMinutes uint32                `idl:"name:SpanMinutes" json:"span_minutes"`
	Flags       csvp.ClusterLogExFlag `idl:"name:flags" json:"flags"`
	// NoCollate: If TRUE and if the generated cluster log would consist of multiple sections,
	// individual sections of the log file SHOULD<58> be generated into separate files in
	// LogFilePath.
	NoCollate bool `idl:"name:NoCollate" json:"no_collate"`
}

func (o *GenerateLogEx2Request) xxx_ToOp(ctx context.Context, op *xxx_GenerateLogEx2Operation) *xxx_GenerateLogEx2Operation {
	if op == nil {
		op = &xxx_GenerateLogEx2Operation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.Type = o.Type
	op.SpanMinutes = o.SpanMinutes
	op.Flags = o.Flags
	op.NoCollate = o.NoCollate
	return op
}

func (o *GenerateLogEx2Request) xxx_FromOp(ctx context.Context, op *xxx_GenerateLogEx2Operation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.Type = op.Type
	o.SpanMinutes = op.SpanMinutes
	o.Flags = op.Flags
	o.NoCollate = op.NoCollate
}
func (o *GenerateLogEx2Request) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *GenerateLogEx2Request) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_GenerateLogEx2Operation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeGenerateLogEx2Request build a response structure from the given request structure.
func (o *GenerateLogEx2Request) MakeResponse() *GenerateLogEx2Response {
	return &GenerateLogEx2Response{}
}

// OpNum returns the operation number of GenerateLogEx2 operation.
func (o *GenerateLogEx2Request) OpNum() int { return 12 }

// OpName returns the operation name of GenerateLogEx2 operation.
func (o *GenerateLogEx2Request) OpName() string { return "/IClusterLogEx3/v0/GenerateLogEx2" }

// GenerateLogEx2Response structure represents the GenerateLogEx2 operation response
type GenerateLogEx2Response struct {
	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That         *dcom.ORPCThat `idl:"name:That" json:"that"`
	LongFilePath *oaut.String   `idl:"name:LongFilePath" json:"long_file_path"`
	// SemicolonSeperatedLogFilesPath: Upon successful completion of this method, the server
	// MUST set this parameter to a semicolon-delimited list of all the files generated
	// into the path specified by LogFilePath. On unsuccessful completion of this method,
	// the client MUST ignore this value.
	SemicolonSeperatedLogFilesPath *oaut.String `idl:"name:SemicolonSeperatedLogFilesPath" json:"semicolon_seperated_log_files_path"`
	// Return: The GenerateLogEx2 return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *GenerateLogEx2Response) xxx_ToOp(ctx context.Context, op *xxx_GenerateLogEx2Operation) *xxx_GenerateLogEx2Operation {
	if op == nil {
		op = &xxx_GenerateLogEx2Operation{}
	}
	if o == nil {
		return op
	}
	op.That = o.That
	op.LongFilePath = o.LongFilePath
	op.SemicolonSeperatedLogFilesPath = o.SemicolonSeperatedLogFilesPath
	op.Return = o.Return
	return op
}

func (o *GenerateLogEx2Response) xxx_FromOp(ctx context.Context, op *xxx_GenerateLogEx2Operation) {
	if o == nil {
		return
	}
	o.That = op.That
	o.LongFilePath = op.LongFilePath
	o.SemicolonSeperatedLogFilesPath = op.SemicolonSeperatedLogFilesPath
	o.Return = op.Return
}
func (o *GenerateLogEx2Response) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *GenerateLogEx2Response) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_GenerateLogEx2Operation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}
