import "guiddef.h";

typedef GUID uuid_t;

[uuid(333a2276-0000-0000-0d00-00809c000000), version(3)] 
interface conv
{
    /*
     * C O N V _ W H O _ A R E _ Y O U
     */
    
    [idempotent] 
    void conv_who_are_you(
            [in]    handle_t        h,
            [in]    uuid_t          *actuid,
            [in]    unsigned32      boot_time,
            [out]   unsigned32      *seq,
            [out]   unsigned32      *st
    );
    
    /*
     * C O N V _ W H O _ A R E _ Y O U 2
     */
    
    [idempotent] 
    void conv_who_are_you2(
            [in]    handle_t        h,
            [in]    uuid_t          *actuid,
            [in]    unsigned32      boot_time,
            [out]   unsigned32      *seq,
            [out]   uuid_t          *cas_uuid,
            [out]   unsigned32      *st
    );
    
    /*
     * C O N V _ A R E _ Y O U _ T H E R E
     */
    
    [idempotent] 
    void conv_are_you_there(
            [in]    handle_t        h,
            [in]    uuid_t          *actuid,
            [in]    unsigned32      boot_time,
            [out]   unsigned32      *st
    );
    
    /*
     * C O N V _ W H O _ A R E _ Y O U _ A U T H
     */
    
    [idempotent] 
    void conv_who_are_you_auth(
            [in]    handle_t        h,
            [in]    uuid_t          *actuid,
            [in]    unsigned32      boot_time,
            [in, size_is(in_len)]    
                    byte            in_data[],
            [in]    signed32        in_len,
            [in]    signed32        out_max_len,
            [out]   unsigned32      *seq,
            [out]   uuid_t          *cas_uuid,
            [out, length_is(*out_len), size_is(out_max_len)]    
                    byte            out_data[],
            [out]   signed32        *out_len,
            [out]   unsigned32      *st
    );

    /*
     * C O N V _ W H O _ A R E _ Y O U _ A U T H _ M O R E
     */

    [idempotent]
    void conv_who_are_you_auth_more(
            [in]    handle_t        h,
            [in]    uuid_t          *actuid,
            [in]    unsigned32      boot_time,
            [in]    signed32        index,
            [in]    signed32        out_max_len,
            [out, length_is(*out_len), size_is(out_max_len)]
                    byte            out_data[],
            [out]   signed32        *out_len,
            [out]   unsigned32      *st
    );

}

[uuid(4a967f14-3000-0000-0d00-012882000000), version(1)] 
interface convc
{
    /*
     * C O N V C _ I N D Y
     */
    
    [maybe] 
    void convc_indy(
            [in]    handle_t        h,
            [in]    uuid_t          *cas_uuid
    );
}
