// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package iclusterlogex2

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	dcom "github.com/oiweiwei/go-msrpc/msrpc/dcom"
	csvp "github.com/oiweiwei/go-msrpc/msrpc/dcom/csvp"
	iclusterlogex "github.com/oiweiwei/go-msrpc/msrpc/dcom/csvp/iclusterlogex/v0"
	oaut "github.com/oiweiwei/go-msrpc/msrpc/dcom/oaut"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = dcom.GoPackage
	_ = iclusterlogex.GoPackage
	_ = csvp.GoPackage
	_ = oaut.GoPackage
)

var (
	// import guard
	GoPackage = "dcom/csvp"
)

var (
	// IClusterLogEx2 interface identifier 2510ea7d-c355-40c9-852c-e3b1b1338d67
	ClusterLogEx2IID = &dcom.IID{Data1: 0x2510ea7d, Data2: 0xc355, Data3: 0x40c9, Data4: []byte{0x85, 0x2c, 0xe3, 0xb1, 0xb1, 0x33, 0x8d, 0x67}}
	// Syntax UUID
	ClusterLogEx2SyntaxUUID = &uuid.UUID{TimeLow: 0x2510ea7d, TimeMid: 0xc355, TimeHiAndVersion: 0x40c9, ClockSeqHiAndReserved: 0x85, ClockSeqLow: 0x2c, Node: [6]uint8{0xe3, 0xb1, 0xb1, 0x33, 0x8d, 0x67}}
	// Syntax ID
	ClusterLogEx2SyntaxV0_0 = &dcerpc.SyntaxID{IfUUID: ClusterLogEx2SyntaxUUID, IfVersionMajor: 0, IfVersionMinor: 0}
)

// IClusterLogEx2 interface.
type ClusterLogEx2Client interface {

	// IClusterLogEx retrieval method.
	ClusterLogEx() iclusterlogex.ClusterLogExClient

	// The GenerateLogEx method<52> writes a file that contains diagnostic information about
	// failover clusters for the server on which it executes. The content and format of
	// the file are implementation-specific but SHOULD contain diagnostic information.
	//
	// Return Values: A signed 32-bit value that indicates return status. If the method
	// returns a negative value, it has failed. Zero or positive values indicate success,
	// with the lower 16 bits in positive nonzero values containing warnings or flags defined
	// in the method implementation. For more information about Microsoft Win32 error codes
	// and HRESULT values, see [MS-ERREF] sections 2.2 and 2.1.
	//
	//	+-------------------+--------------------------+
	//	|      RETURN       |                          |
	//	|    VALUE/CODE     |       DESCRIPTION        |
	//	|                   |                          |
	//	+-------------------+--------------------------+
	//	+-------------------+--------------------------+
	//	| 0x00000000 S_OK   | The call was successful. |
	//	+-------------------+--------------------------+
	//
	// For any other condition, this method MUST return a value that is not one of the values
	// listed in the preceding table. The client MUST behave in an identical manner for
	// all return values not listed in the preceding table.
	//
	// Exceptions Thrown: No exceptions are thrown beyond those thrown by the underlying
	// RPC protocol [MS-RPCE].
	//
	// The opnum field value for this method is 9.
	GenerateLogEx(context.Context, *GenerateLogExRequest, ...dcerpc.CallOption) (*GenerateLogExResponse, error)

	// The GetCountLogs method<54> returns the number of log files that were generated by
	// a preceding call to the GenerateLogEx method (section 3.19.4.1).
	//
	// Return Values: A signed 32-bit value that indicates return status. If the method
	// returns a negative value, it has failed. Zero or positive values indicate success,
	// with the lower 16 bits in positive nonzero values containing warnings or flags defined
	// in the method implementation. For more information about Microsoft Win32 error codes
	// and HRESULT values, see [MS-ERREF] sections 2.2 and 2.1.
	//
	//	+-------------------+--------------------------+
	//	|      RETURN       |                          |
	//	|    VALUE/CODE     |       DESCRIPTION        |
	//	|                   |                          |
	//	+-------------------+--------------------------+
	//	+-------------------+--------------------------+
	//	| 0x00000000 S_OK   | The call was successful. |
	//	+-------------------+--------------------------+
	//
	// For any other condition, this method MUST return a value that is not one of the values
	// listed in the preceding table. The client MUST behave in an identical manner for
	// all return values not listed in the preceding table.
	//
	// Exceptions Thrown: No exceptions are thrown beyond those thrown by the underlying
	// RPC protocol [MS-RPCE].
	//
	// The opnum field value for this method is 10.
	GetCountLogs(context.Context, *GetCountLogsRequest, ...dcerpc.CallOption) (*GetCountLogsResponse, error)

	// The GetLogFilePath method<55> returns the server-relative path of a log file that
	// was generated by a preceding call to the GenerateLogEx method (section 3.19.4.1).
	//
	// Return Values: A signed 32-bit value that indicates return status. If the method
	// returns a negative value, it has failed. Zero or positive values indicate success,
	// with the lower 16 bits in positive nonzero values containing warnings or flags defined
	// in the method implementation. For more information about Win32 error codes and HRESULT
	// values, see [MS-ERREF] section 2.2 and 2.1.
	//
	//	+--------------------------+-------------------------------------------------------+
	//	|          RETURN          |                                                       |
	//	|        VALUE/CODE        |                      DESCRIPTION                      |
	//	|                          |                                                       |
	//	+--------------------------+-------------------------------------------------------+
	//	+--------------------------+-------------------------------------------------------+
	//	| 0x00000000 S_OK          | The call was successful.                              |
	//	+--------------------------+-------------------------------------------------------+
	//	| 0x8007000E E_OUTOFMEMORY | Index is out of range for the list of available logs. |
	//	+--------------------------+-------------------------------------------------------+
	//
	// For any other condition, this method MUST return a value that is not one of the values
	// listed in the preceding table. The client MUST behave in an identical manner for
	// all return values not listed in the preceding table.
	//
	// Exceptions Thrown: No exceptions are thrown beyond those thrown by the underlying
	// RPC protocol [MS-RPCE]
	//
	// The opnum field value for this method is 11.
	GetLogFilePath(context.Context, *GetLogFilePathRequest, ...dcerpc.CallOption) (*GetLogFilePathResponse, error)

	// AlterContext alters the client context.
	AlterContext(context.Context, ...dcerpc.Option) error

	// Conn returns the client connection (unsafe)
	Conn() dcerpc.Conn

	// IPID sets the object interface identifier.
	IPID(context.Context, *dcom.IPID) ClusterLogEx2Client
}

type xxx_DefaultClusterLogEx2Client struct {
	iclusterlogex.ClusterLogExClient
	cc   dcerpc.Conn
	ipid *dcom.IPID
}

func (o *xxx_DefaultClusterLogEx2Client) ClusterLogEx() iclusterlogex.ClusterLogExClient {
	return o.ClusterLogExClient
}

func (o *xxx_DefaultClusterLogEx2Client) GenerateLogEx(ctx context.Context, in *GenerateLogExRequest, opts ...dcerpc.CallOption) (*GenerateLogExResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &GenerateLogExResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultClusterLogEx2Client) GetCountLogs(ctx context.Context, in *GetCountLogsRequest, opts ...dcerpc.CallOption) (*GetCountLogsResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &GetCountLogsResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultClusterLogEx2Client) GetLogFilePath(ctx context.Context, in *GetLogFilePathRequest, opts ...dcerpc.CallOption) (*GetLogFilePathResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &GetLogFilePathResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultClusterLogEx2Client) AlterContext(ctx context.Context, opts ...dcerpc.Option) error {
	return o.cc.AlterContext(ctx, opts...)
}

func (o *xxx_DefaultClusterLogEx2Client) Conn() dcerpc.Conn {
	return o.cc
}

func (o *xxx_DefaultClusterLogEx2Client) IPID(ctx context.Context, ipid *dcom.IPID) ClusterLogEx2Client {
	if ipid == nil {
		ipid = &dcom.IPID{}
	}
	return &xxx_DefaultClusterLogEx2Client{
		ClusterLogExClient: o.ClusterLogExClient.IPID(ctx, ipid),
		cc:                 o.cc,
		ipid:               ipid,
	}
}

func NewClusterLogEx2Client(ctx context.Context, cc dcerpc.Conn, opts ...dcerpc.Option) (ClusterLogEx2Client, error) {
	var err error
	if !dcom.IsSuperclass(opts) {
		cc, err = cc.Bind(ctx, append(opts, dcerpc.WithAbstractSyntax(ClusterLogEx2SyntaxV0_0))...)
		if err != nil {
			return nil, err
		}
	}
	base, err := iclusterlogex.NewClusterLogExClient(ctx, cc, append(opts, dcom.Superclass(cc))...)
	if err != nil {
		return nil, err
	}
	ipid, ok := dcom.HasIPID(opts)
	if ok {
		base = base.IPID(ctx, ipid)
	}
	return &xxx_DefaultClusterLogEx2Client{
		ClusterLogExClient: base,
		cc:                 cc,
		ipid:               ipid,
	}, nil
}

// xxx_GenerateLogExOperation structure represents the GenerateLogEx operation
type xxx_GenerateLogExOperation struct {
	This        *dcom.ORPCThis        `idl:"name:This" json:"this"`
	That        *dcom.ORPCThat        `idl:"name:That" json:"that"`
	Type        csvp.ClusterLogType   `idl:"name:Type" json:"type"`
	SpanMinutes uint32                `idl:"name:SpanMinutes" json:"span_minutes"`
	Flags       csvp.ClusterLogExFlag `idl:"name:flags" json:"flags"`
	LogFilePath *oaut.String          `idl:"name:LogFilePath" json:"log_file_path"`
	NoCollate   bool                  `idl:"name:NoCollate" json:"no_collate"`
	Return      int32                 `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of GenerateLogEx operation.
func (o *xxx_GenerateLogExOperation) OpNum() int { return 9 }

// OpName returns the operation name of GenerateLogEx operation.
func (o *xxx_GenerateLogExOperation) OpName() string { return "/IClusterLogEx2/v0/GenerateLogEx" }

func (o *xxx_GenerateLogExOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GenerateLogExOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Type {in} (1:{alias=ClusterLogType}(enum))
	{
		if err := w.WriteEnum(uint16(o.Type)); err != nil {
			return err
		}
	}
	// SpanMinutes {in} (1:{alias=ULONG}(uint32))
	{
		if err := w.WriteData(o.SpanMinutes); err != nil {
			return err
		}
	}
	// flags {in} (1:{alias=ClusterLogExFlag}(enum))
	{
		if err := w.WriteEnum(uint16(o.Flags)); err != nil {
			return err
		}
	}
	// NoCollate {in} (1:{alias=BOOL}(int32))
	{
		if !o.NoCollate {
			if err := w.WriteData(int32(0)); err != nil {
				return err
			}
		} else {
			if err := w.WriteData(int32(1)); err != nil {
				return err
			}
		}
	}
	return nil
}

func (o *xxx_GenerateLogExOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Type {in} (1:{alias=ClusterLogType}(enum))
	{
		if err := w.ReadEnum((*uint16)(&o.Type)); err != nil {
			return err
		}
	}
	// SpanMinutes {in} (1:{alias=ULONG}(uint32))
	{
		if err := w.ReadData(&o.SpanMinutes); err != nil {
			return err
		}
	}
	// flags {in} (1:{alias=ClusterLogExFlag}(enum))
	{
		if err := w.ReadEnum((*uint16)(&o.Flags)); err != nil {
			return err
		}
	}
	// NoCollate {in} (1:{alias=BOOL}(int32))
	{
		var _bNoCollate int32
		if err := w.ReadData(&_bNoCollate); err != nil {
			return err
		}
		o.NoCollate = _bNoCollate != 0
	}
	return nil
}

func (o *xxx_GenerateLogExOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GenerateLogExOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// LogFilePath {out} (1:{pointer=ref}*(2))(2:{pointer=unique, alias=BSTR}*(1))(3:{pointer=unique, alias=_BSTR, names=FLAGGED_WORD_BLOB}(struct))
	{
		if o.LogFilePath != nil {
			_ptr_LogFilePath := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				if o.LogFilePath != nil {
					if err := o.LogFilePath.MarshalNDR(ctx, w); err != nil {
						return err
					}
				} else {
					if err := (&oaut.String{}).MarshalNDR(ctx, w); err != nil {
						return err
					}
				}
				return nil
			})
			if err := w.WritePointer(&o.LogFilePath, _ptr_LogFilePath); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GenerateLogExOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// LogFilePath {out} (1:{pointer=ref}*(2))(2:{pointer=unique, alias=BSTR}*(1))(3:{pointer=unique, alias=_BSTR, names=FLAGGED_WORD_BLOB}(struct))
	{
		_ptr_LogFilePath := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if o.LogFilePath == nil {
				o.LogFilePath = &oaut.String{}
			}
			if err := o.LogFilePath.UnmarshalNDR(ctx, w); err != nil {
				return err
			}
			return nil
		})
		_s_LogFilePath := func(ptr interface{}) { o.LogFilePath = *ptr.(**oaut.String) }
		if err := w.ReadPointer(&o.LogFilePath, _s_LogFilePath, _ptr_LogFilePath); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// GenerateLogExRequest structure represents the GenerateLogEx operation request
type GenerateLogExRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This *dcom.ORPCThis `idl:"name:This" json:"this"`
	// Type: Is of type ClusterLogType enum as specified in section 2.2.28.
	Type csvp.ClusterLogType `idl:"name:Type" json:"type"`
	// SpanMinutes: A value, in minutes, that indicates those values that SHOULD be in the
	// log. Events that occurred in the range of Now to (Now – SpanMinutes) MUST be in
	// the log and no others. Now is the GMT on the server.
	SpanMinutes uint32                `idl:"name:SpanMinutes" json:"span_minutes"`
	Flags       csvp.ClusterLogExFlag `idl:"name:flags" json:"flags"`
	// NoCollate: If TRUE and if the generated cluster log would consist of multiple sections,
	// individual sections of the log file SHOULD<53> be generated into separate files in
	// LogFilePath.
	NoCollate bool `idl:"name:NoCollate" json:"no_collate"`
}

func (o *GenerateLogExRequest) xxx_ToOp(ctx context.Context, op *xxx_GenerateLogExOperation) *xxx_GenerateLogExOperation {
	if op == nil {
		op = &xxx_GenerateLogExOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.Type = o.Type
	op.SpanMinutes = o.SpanMinutes
	op.Flags = o.Flags
	op.NoCollate = o.NoCollate
	return op
}

func (o *GenerateLogExRequest) xxx_FromOp(ctx context.Context, op *xxx_GenerateLogExOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.Type = op.Type
	o.SpanMinutes = op.SpanMinutes
	o.Flags = op.Flags
	o.NoCollate = op.NoCollate
}
func (o *GenerateLogExRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *GenerateLogExRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_GenerateLogExOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeGenerateLogExRequest build a response structure from the given request structure.
func (o *GenerateLogExRequest) MakeResponse() *GenerateLogExResponse {
	return &GenerateLogExResponse{}
}

// OpNum returns the operation number of GenerateLogEx operation.
func (o *GenerateLogExRequest) OpNum() int { return 9 }

// OpName returns the operation name of GenerateLogEx operation.
func (o *GenerateLogExRequest) OpName() string { return "/IClusterLogEx2/v0/GenerateLogEx" }

// GenerateLogExResponse structure represents the GenerateLogEx operation response
type GenerateLogExResponse struct {
	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That *dcom.ORPCThat `idl:"name:That" json:"that"`
	// LogFilePath: Upon successful completion of this method, the server MUST set this
	// parameter to the location where the server has exposed a file containing the diagnostic
	// log data. The path is relative to the machine and starts with a share name. The format
	// is "<share>\<filename>" where <share> is a share name, and <filename> is the name
	// of the file or device. The LogFilePath parameter MUST form a valid UncPath if \\servername>\
	// is prepended to its contents. On unsuccessful completion of this method, the client
	// MUST ignore this value.
	LogFilePath *oaut.String `idl:"name:LogFilePath" json:"log_file_path"`
	// Return: The GenerateLogEx return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *GenerateLogExResponse) xxx_ToOp(ctx context.Context, op *xxx_GenerateLogExOperation) *xxx_GenerateLogExOperation {
	if op == nil {
		op = &xxx_GenerateLogExOperation{}
	}
	if o == nil {
		return op
	}
	op.That = o.That
	op.LogFilePath = o.LogFilePath
	op.Return = o.Return
	return op
}

func (o *GenerateLogExResponse) xxx_FromOp(ctx context.Context, op *xxx_GenerateLogExOperation) {
	if o == nil {
		return
	}
	o.That = op.That
	o.LogFilePath = op.LogFilePath
	o.Return = op.Return
}
func (o *GenerateLogExResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *GenerateLogExResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_GenerateLogExOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// xxx_GetCountLogsOperation structure represents the GetCountLogs operation
type xxx_GetCountLogsOperation struct {
	This   *dcom.ORPCThis `idl:"name:This" json:"this"`
	That   *dcom.ORPCThat `idl:"name:That" json:"that"`
	Count  uint32         `idl:"name:Count" json:"count"`
	Return int32          `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of GetCountLogs operation.
func (o *xxx_GetCountLogsOperation) OpNum() int { return 10 }

// OpName returns the operation name of GetCountLogs operation.
func (o *xxx_GetCountLogsOperation) OpName() string { return "/IClusterLogEx2/v0/GetCountLogs" }

func (o *xxx_GetCountLogsOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetCountLogsOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetCountLogsOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetCountLogsOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetCountLogsOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Count {out} (1:{pointer=ref}*(1))(2:{alias=ULONG}(uint32))
	{
		if err := w.WriteData(o.Count); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetCountLogsOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Count {out} (1:{pointer=ref}*(1))(2:{alias=ULONG}(uint32))
	{
		if err := w.ReadData(&o.Count); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// GetCountLogsRequest structure represents the GetCountLogs operation request
type GetCountLogsRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This *dcom.ORPCThis `idl:"name:This" json:"this"`
}

func (o *GetCountLogsRequest) xxx_ToOp(ctx context.Context, op *xxx_GetCountLogsOperation) *xxx_GetCountLogsOperation {
	if op == nil {
		op = &xxx_GetCountLogsOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	return op
}

func (o *GetCountLogsRequest) xxx_FromOp(ctx context.Context, op *xxx_GetCountLogsOperation) {
	if o == nil {
		return
	}
	o.This = op.This
}
func (o *GetCountLogsRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *GetCountLogsRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_GetCountLogsOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeGetCountLogsRequest build a response structure from the given request structure.
func (o *GetCountLogsRequest) MakeResponse() *GetCountLogsResponse {
	return &GetCountLogsResponse{}
}

// OpNum returns the operation number of GetCountLogs operation.
func (o *GetCountLogsRequest) OpNum() int { return 10 }

// OpName returns the operation name of GetCountLogs operation.
func (o *GetCountLogsRequest) OpName() string { return "/IClusterLogEx2/v0/GetCountLogs" }

// GetCountLogsResponse structure represents the GetCountLogs operation response
type GetCountLogsResponse struct {
	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That *dcom.ORPCThat `idl:"name:That" json:"that"`
	// Count: The number of log files generated by a preceding call to GenerateLogEx (section
	// 3.19.4.1).
	Count uint32 `idl:"name:Count" json:"count"`
	// Return: The GetCountLogs return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *GetCountLogsResponse) xxx_ToOp(ctx context.Context, op *xxx_GetCountLogsOperation) *xxx_GetCountLogsOperation {
	if op == nil {
		op = &xxx_GetCountLogsOperation{}
	}
	if o == nil {
		return op
	}
	op.That = o.That
	op.Count = o.Count
	op.Return = o.Return
	return op
}

func (o *GetCountLogsResponse) xxx_FromOp(ctx context.Context, op *xxx_GetCountLogsOperation) {
	if o == nil {
		return
	}
	o.That = op.That
	o.Count = op.Count
	o.Return = op.Return
}
func (o *GetCountLogsResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *GetCountLogsResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_GetCountLogsOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// xxx_GetLogFilePathOperation structure represents the GetLogFilePath operation
type xxx_GetLogFilePathOperation struct {
	This        *dcom.ORPCThis `idl:"name:This" json:"this"`
	That        *dcom.ORPCThat `idl:"name:That" json:"that"`
	Index       uint32         `idl:"name:Index" json:"index"`
	LogFilePath *oaut.String   `idl:"name:LogFilePath" json:"log_file_path"`
	Return      int32          `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of GetLogFilePath operation.
func (o *xxx_GetLogFilePathOperation) OpNum() int { return 11 }

// OpName returns the operation name of GetLogFilePath operation.
func (o *xxx_GetLogFilePathOperation) OpName() string { return "/IClusterLogEx2/v0/GetLogFilePath" }

func (o *xxx_GetLogFilePathOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetLogFilePathOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Index {in} (1:{alias=ULONG}(uint32))
	{
		if err := w.WriteData(o.Index); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetLogFilePathOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Index {in} (1:{alias=ULONG}(uint32))
	{
		if err := w.ReadData(&o.Index); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetLogFilePathOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetLogFilePathOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// LogFilePath {out} (1:{pointer=ref}*(2))(2:{pointer=unique, alias=BSTR}*(1))(3:{pointer=unique, alias=_BSTR, names=FLAGGED_WORD_BLOB}(struct))
	{
		if o.LogFilePath != nil {
			_ptr_LogFilePath := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				if o.LogFilePath != nil {
					if err := o.LogFilePath.MarshalNDR(ctx, w); err != nil {
						return err
					}
				} else {
					if err := (&oaut.String{}).MarshalNDR(ctx, w); err != nil {
						return err
					}
				}
				return nil
			})
			if err := w.WritePointer(&o.LogFilePath, _ptr_LogFilePath); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetLogFilePathOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// LogFilePath {out} (1:{pointer=ref}*(2))(2:{pointer=unique, alias=BSTR}*(1))(3:{pointer=unique, alias=_BSTR, names=FLAGGED_WORD_BLOB}(struct))
	{
		_ptr_LogFilePath := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if o.LogFilePath == nil {
				o.LogFilePath = &oaut.String{}
			}
			if err := o.LogFilePath.UnmarshalNDR(ctx, w); err != nil {
				return err
			}
			return nil
		})
		_s_LogFilePath := func(ptr interface{}) { o.LogFilePath = *ptr.(**oaut.String) }
		if err := w.ReadPointer(&o.LogFilePath, _s_LogFilePath, _ptr_LogFilePath); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// GetLogFilePathRequest structure represents the GetLogFilePath operation request
type GetLogFilePathRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This *dcom.ORPCThis `idl:"name:This" json:"this"`
	// Index: The index of the log file generated by a preceding call to GenerateLogEx (section
	// 3.19.4.1).
	Index uint32 `idl:"name:Index" json:"index"`
}

func (o *GetLogFilePathRequest) xxx_ToOp(ctx context.Context, op *xxx_GetLogFilePathOperation) *xxx_GetLogFilePathOperation {
	if op == nil {
		op = &xxx_GetLogFilePathOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.Index = o.Index
	return op
}

func (o *GetLogFilePathRequest) xxx_FromOp(ctx context.Context, op *xxx_GetLogFilePathOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.Index = op.Index
}
func (o *GetLogFilePathRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *GetLogFilePathRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_GetLogFilePathOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeGetLogFilePathRequest build a response structure from the given request structure.
func (o *GetLogFilePathRequest) MakeResponse() *GetLogFilePathResponse {
	return &GetLogFilePathResponse{}
}

// OpNum returns the operation number of GetLogFilePath operation.
func (o *GetLogFilePathRequest) OpNum() int { return 11 }

// OpName returns the operation name of GetLogFilePath operation.
func (o *GetLogFilePathRequest) OpName() string { return "/IClusterLogEx2/v0/GetLogFilePath" }

// GetLogFilePathResponse structure represents the GetLogFilePath operation response
type GetLogFilePathResponse struct {
	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That *dcom.ORPCThat `idl:"name:That" json:"that"`
	// LogFilePath: Upon successful completion of this method, the server MUST set this
	// parameter to the location where the server has exposed a file containing the requested
	// diagnostic log data. The path is relative to the machine and starts with a share
	// name. The format is "<share>\<filename>" where <share> is a share name, and <filename>
	// is the name of the file or device. The LogFilePath parameter MUST form a valid UncPath
	// if \\servername>\ is prepended to its contents. On unsuccessful completion of this
	// method, the client MUST ignore this value.
	LogFilePath *oaut.String `idl:"name:LogFilePath" json:"log_file_path"`
	// Return: The GetLogFilePath return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *GetLogFilePathResponse) xxx_ToOp(ctx context.Context, op *xxx_GetLogFilePathOperation) *xxx_GetLogFilePathOperation {
	if op == nil {
		op = &xxx_GetLogFilePathOperation{}
	}
	if o == nil {
		return op
	}
	op.That = o.That
	op.LogFilePath = o.LogFilePath
	op.Return = o.Return
	return op
}

func (o *GetLogFilePathResponse) xxx_FromOp(ctx context.Context, op *xxx_GetLogFilePathOperation) {
	if o == nil {
		return
	}
	o.That = op.That
	o.LogFilePath = op.LogFilePath
	o.Return = op.Return
}
func (o *GetLogFilePathResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *GetLogFilePathResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_GetLogFilePathOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}
